name: pulse-and-heritage
domains:
- domain: pulseandheritage.com
  type: PRIMARY
- domain: www.pulseandheritage.com
  type: ALIAS
static_sites:
- name: web
  git:
    repo_clone_url: https://github.com/Hell0pr0to/pulse-and-heritage.git
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
